# signup user

POST http://127.0.0.1:4000/auth/signup
Content-Type: application/json

{
  "username": "mrlectus",
  "password": "123456"
}

# user signin

POST http://127.0.0.1:4000/auth/login
Content-Type: application/json

{
  "username": "mrlectus",
  "password": "123456"
}

# @lang=lua
---{%
  local body = vim.json.decode(response.body)
  vim.fn.set_env("username", body.user.username)
  vim.fn.set_env("id", body.user.id)
  vim.fn.set_env("token", body.user.token)
---%}

###
# user add habit

POST http://127.0.0.1:4000/habit
Content-Type: application/json

{
  "name": "Buy all the Burgers (2)",
  "frequency": "Weekly",
  "startDate": "2024-08-21T12:01:10Z",
  "description": "Daily",
  "userId": "{{id}}"
}

# user get habit
# the id is the habit id

GET http://127.0.0.1:4000/habit/cm03t1jol0001kxuur8medx1h
Content-Type: application/json

### user Patch habit habit - Habit name
### the id is the habit id

PATCH http://127.0.0.1:4000/habit/cm03t1jol0001kxuur8medx1h
Content-Type: application/json

{
  "name": "Press my cloths after wash (20)"
}

# user Patch habit habit - Habit name
# the id is the habit id

DELETE http://127.0.0.1:4000/habit/cm04mx5eu000119a7g7xs16r7
Content-Type: application/json

### user add habit logs
# the id is the habit id

POST http://127.0.0.1:4000/habit/log/daily
Content-Type: application/json

{
  "date": "2024-08-25T20:35:38Z",
  "habitId": "clziuxbma00011r8480cn5ajq",
  "status": "Done"
}

### user add habit logs weekly
# the id is the habit id

POST http://127.0.0.1:4000/habit/log/weekly
Content-Type: application/json

{
  "date": "2024-08-25T20:35:38Z",
  "habitId": "clziuxbma00011r8480cn5ajq",
  "status": "Done"
}


# user all info on user
# the id is the user id

GET http://127.0.0.1:4000/users/{{id}}
Content-Type: application/json

### Get user daily habit
# the id is the user id

GET http://127.0.0.1:4000/users/habit/daily/{{id}}
Content-Type: application/json

### Get user daily habit count
# the id is the user id

GET http://127.0.0.1:4000/users/habit/daily/{{id}}/count
Content-Type: application/json

### Get user weekly habit
# the id is the user id

GET http://127.0.0.1:4000/users/habit/weekly/{{id}}
Content-Type: application/json

### Get user weekly habit count
# the id is the user id

GET http://127.0.0.1:4000/users/habit/weekly/{{id}}/count
Content-Type: application/json

### Get user Daily logs
# the id is the user id

GET http://127.0.0.1:4000/habit/log/{{id}}/daily
Content-Type: application/json

### Get user Daily logs
# the id is the user id

GET http://127.0.0.1:4000/habit/log/{{id}}/weekly
Content-Type: application/json
